services:
  - type: web_service
    name: ComlabManagementSystemAnomalies
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn your_app:app
